version: 1.0.0
title: "{{ project_name }} Code Review" # Wrap the value in quotes if it starts with template syntax to avoid YAML parsing errors
description: Automated code review for {{ project_name }} with {{ language }} focus
instructions: |
   You are a code reviewer specialized in {{ language }} development.
   Apply the following standards:
   - Complexity threshold: {{ complexity_threshold }}
   - Required test coverage: {{ test_coverage }}%
   - Style guide: {{ style_guide }}
activities:
- "Review {{ language }} code for complexity"
- "Check test coverage against {{ test_coverage }}% requirement"
- "Verify {{ style_guide }} compliance"
settings:                     
  goose_provider: "{{goose_provider}}" 
  goose_model: "{{goose_model}}"           
  temperature: {{temperature}}    #unable to set as parameter, got map error using number
parameters:
- key: goose_provider
  input_type: string
  requirement: optional
  default: anthropic
  description: llm provider to use
- key: goose_model
  input_type: string
  requirement: optional
  default: claude-3-sonnet
  description: llm model to use
- key: temperature
  input_type: number
  requirement: optional
  default: 0.7 # default is required for optional parameters
  description: temperature setting higher is more creative
- key: project_name
  input_type: string
  requirement: required # could be required, optional or user_prompt
  description: name of the project
- key: language
  input_type: string
  requirement: required
  description: language of the code
- key: complexity_threshold
  input_type: number
  requirement: optional
  default: 20 # default is required for optional parameters
  description: a threshold that defines the maximum allowed complexity
- key: test_coverage
  input_type: number
  requirement: optional
  default: 80
  description: the minimum test coverage threshold in percentage
- key: style_guide
  input_type: string
  description: style guide name
  requirement: user_prompt
  # If style_guide param value is not specified in the command, user will be prompted to provide a value, even in non-interactive modea
